# Generated by Django 4.0.3 on 2022-03-10 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('medication', '0001_initial'), ('medication', '0002_alter_medicine_options'), ('medication', '0003_medicineschedule_tolerance_mins_and_more'), ('medication', '0004_alter_medicineconsumption_options_and_more'), ('medication', '0005_rename_medicineconsumption_consumption_and_more'), ('medication', '0006_alter_schedule_frequency_in_days_and_more'), ('medication', '0007_medicine_current_balance_ledgerentry'), ('medication', '0008_alter_consumption_table_alter_ledgerentry_table_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_balance', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.medicine')),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency_in_days', models.PositiveSmallIntegerField(default=1)),
                ('time', models.TimeField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.medicine')),
                ('tolerance_mins', models.PositiveSmallIntegerField(choices=[(5, '5m'), (10, '10m'), (15, '15m'), (20, '20m'), (30, '30m'), (45, '45m'), (60, '1h'), (90, '1.5h'), (120, '2h')], default=30, verbose_name='Tolerance (mins)')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('quantity', models.SmallIntegerField()),
                ('consumption', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medication.consumption')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.medicine')),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
        migrations.AlterModelTable(
            name='consumption',
            table='consumption',
        ),
        migrations.AlterModelTable(
            name='ledgerentry',
            table='ledgerentry',
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='medicine',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
    ]
