# Generated by Django 4.0.3 on 2022-03-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_alter_medicine_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineschedule',
            name='tolerance_mins',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Tolerance (mins)'),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
