# Generated by Django 4.0.3 on 2022-03-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_medicineschedule_tolerance_mins_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicineconsumption',
            options={'ordering': ['-when']},
        ),
        migrations.AlterModelOptions(
            name='medicineschedule',
            options={'ordering': ['-end_date']},
        ),
    ]
