# Generated by Django 4.0.3 on 2022-03-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0005_rename_medicineconsumption_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='frequency_in_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tolerance_mins',
            field=models.PositiveSmallIntegerField(choices=[(5, '5m'), (10, '10m'), (15, '15m'), (20, '20m'), (30, '30m'), (45, '45m'), (60, '1h'), (90, '1.5h'), (120, '2h')], default=30, verbose_name='Tolerance (mins)'),
        ),
    ]
