# Generated by Django 4.0.3 on 2022-03-08 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medication", "0006_alter_schedule_frequency_in_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="current_balance",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField()),
                ("quantity", models.SmallIntegerField()),
                (
                    "consumption",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medication.consumption",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medication.medicine",
                    ),
                ),
            ],
            options={
                "ordering": ["-when"],
            },
        ),
    ]
