# Generated by Django 4.0.3 on 2022-03-01 11:55

from django.db import migrations

def seed_body_areas(apps, _):
    """Inserts default body areas that the app should start with."""
    BodyArea = apps.get_model('body.BodyArea')
    body_areas = (
        ('Scalp', ''),
        ('Forehead', ''),
        ('Eyes', ''),
        ('Face', ''),
        ('Ears', ''),
        ('Neck', 'cm'),
        ('Shoulders', 'cm'),
        ('Bust', 'cm'),
        ('Under bust', 'cm'),
        ('Waist', 'cm'),
        ('Abdomen', ''),
        ('Hips', 'cm'),
        ('Buttocks', ''),
        ('Genitals', ''),
        ('Thighs', 'cm'),
        ('Knees', 'cm'),
        ('Calves', 'cm'),
        ('Feet', 'cm'),
        ('Upper arms', 'cm'),
        ('Forearms', 'cm'),
        ('Hands', 'cm'),
        ('Fingers', ''),
        ('Mouth', ''),
        ('Tongue', ''),
        ('Nose', ''),
    )

    BodyArea.objects.bulk_create(
        [BodyArea(name=name, measurement_unit=unit) for name, unit in body_areas]
        )

def seed_sensations(apps, _):
    """Inserts default sensations that the app should start with."""
    Sensation = apps.get_model('body.Sensation')
    sensations = (
        'Tingling',
        'Sensitive',
        'Sore',
        'Smarting',
        'Pleasurable',
        'Hot',
        'Cold',
        'Stiff',
        'Dry',
        'Sweaty',
        'Numb',
        'Itchy',
        'Irritable',
    )

    Sensation.objects.bulk_create([Sensation(name=name) for name in sensations])


class Migration(migrations.Migration):
    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_body_areas),
        migrations.RunPython(seed_sensations),
    ]
