# Generated by Django 4.0.3 on 2022-03-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_medicine_default_consumption_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyarea',
            options={'ordering': ['order_priority', 'name']},
        ),
        migrations.AddField(
            model_name='bodyarea',
            name='order_priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
