# Generated by Django 4.0.3 on 2022-03-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_auto_20220301_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyarea',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sensation',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='bodyareaentry',
            name='sensations',
            field=models.ManyToManyField(blank=True, to='body.sensation'),
        ),
        migrations.AlterUniqueTogether(
            name='bodyareaentry',
            unique_together={('report', 'body_area')},
        ),
    ]
