# Generated by Django 4.0.3 on 2022-03-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0004_alter_bodyareaentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyareareport',
            name='weight_in_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
