# Generated by Django 4.0.3 on 2022-03-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0005_alter_bodyareareport_weight_in_g'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodyareareport',
            old_name='weight_in_g',
            new_name='weight_in_kg',
        ),
    ]
