# Generated by Django 4.0.3 on 2022-03-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0006_rename_weight_in_g_bodyareareport_weight_in_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyareareport',
            name='weight_in_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)'),
        ),
    ]
