# Generated by Django 4.0.3 on 2022-03-05 23:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('body', '0007_alter_bodyareareport_weight_in_kg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BodyAreaEntry',
            new_name='Entry',
        ),
        migrations.RenameModel(
            old_name='BodyAreaReport',
            new_name='Report',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-when']},
        ),
    ]
