# Generated by Django 4.0.3 on 2022-03-10 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_categories(apps, _):
    """Inserts default categories that the app should start with."""
    category_model = apps.get_model("life_events.Category")
    categories = (
        "Work & Career",
        "Social & Friendship",
        "Health & Fitness",
        "Travel & Experiences",
        "Financial & Organisational",
        "Habits & Goals",
    )

    category_model.objects.bulk_create(
        [category_model(name=name) for name in categories]
    )


class Migration(migrations.Migration):

    replaces = [
        ("life_events", "0001_initial"),
        ("life_events", "0002_category_event_delete_lifeevent"),
        ("life_events", "0003_alter_event_category"),
        ("life_events", "0004_alter_category_table_alter_event_table"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("when", models.DateTimeField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="life_events.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-when"],
            },
        ),
        migrations.RunPython(
            code=seed_categories,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="life_events.category",
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="event",
            table="event",
        ),
    ]
