# Generated by Django 4.0.3 on 2022-03-06 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_categories(apps, _):
    """Inserts default categories that the app should start with."""
    Category = apps.get_model("life_events.Category")
    categories = (
        "Work & Career",
        "Social & Friendship",
        "Health & Fitness",
        "Travel & Experiences",
        "Financial & Organisational",
        "Habits & Goals",
    )

    Category.objects.bulk_create([Category(name=name) for name in categories])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("life_events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("when", models.DateTimeField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="life_events.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-when"],
            },
        ),
        migrations.DeleteModel(
            name="LifeEvent",
        ),
        migrations.RunPython(seed_categories),
    ]
