# Generated by Django 4.0.3 on 2022-03-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life_events', '0003_alter_event_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
