# Generated by Django 4.0.3 on 2022-03-10 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_emotions(apps, _):
    """Inserts default sensations that the app should start with."""
    emotion_model = apps.get_model("mind_and_soul.Emotion")
    emotions = (
        "Surprised",
        "Aroused",
        "Annoyed",
        "Excited",
        "Delighted",
        "Enthusiastic",
        "Glad",
        "Joyful",
        "Content",
        "Serene",
        "At ease",
        "Relaxed",
        "Calm",
        "Irritable",
        "Sleepy",
        "Tired",
        "Bored",
        "Gloomy",
        "Miserable",
        "Depressed",
        "Disgusted",
        "Frustrated",
        "Tense",
        "Afraid",
        "Astonished",
        "Alarmed",
        "Fearful",
        "Angry",
    )

    emotion_model.objects.bulk_create([emotion_model(name=name) for name in emotions])


class Migration(migrations.Migration):

    replaces = [
        ("mind_and_soul", "0001_initial"),
        ("mind_and_soul", "0002_auto_20220302_0027"),
        ("mind_and_soul", "0003_alter_emotion_options"),
        ("mind_and_soul", "0004_alter_emotion_table_alter_emotionentry_table_and_more"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="EmotionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField()),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "energy_level",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmotionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strength", models.PositiveSmallIntegerField()),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "emotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mind_and_soul.emotion",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mind_and_soul.emotionreport",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            code=seed_emotions,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="emotion",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelTable(
            name="emotion",
            table="emotion",
        ),
        migrations.AlterModelTable(
            name="emotionentry",
            table="emotionentry",
        ),
        migrations.AlterModelTable(
            name="emotionreport",
            table="emotionreport",
        ),
    ]
