# Generated by Django 4.0.3 on 2022-03-01 11:55

from django.db import migrations

def seed_emotions(apps, _):
    """Inserts default sensations that the app should start with."""
    Emotion = apps.get_model('mind_and_soul.Emotion')
    emotions = (
        'Surprised',
        'Aroused',
        'Annoyed',
        'Excited',
        'Delighted',
        'Enthusiastic',
        'Glad',
        'Joyful',
        'Content',
        'Serene',
        'At ease',
        'Relaxed',
        'Calm',
        'Irritable',
        'Sleepy',
        'Tired',
        'Bored',
        'Gloomy',
        'Miserable',
        'Depressed',
        'Disgusted',
        'Frustrated',
        'Tense',
        'Afraid',
        'Astonished',
        'Alarmed',
        'Fearful',
        'Angry',
    )

    Emotion.objects.bulk_create([Emotion(name=name) for name in emotions])


class Migration(migrations.Migration):
    dependencies = [
        ('mind_and_soul', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_emotions),
    ]
