# Generated by Django 4.0.3 on 2022-03-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mind_and_soul', '0002_auto_20220302_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotion',
            options={'ordering': ['name']},
        ),
    ]
