# Generated by Django 4.0.3 on 2022-03-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mind_and_soul', '0003_alter_emotion_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emotion',
            table='emotion',
        ),
        migrations.AlterModelTable(
            name='emotionentry',
            table='emotionentry',
        ),
        migrations.AlterModelTable(
            name='emotionreport',
            table='emotionreport',
        ),
    ]
